pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'finalprojet', url: 'https://github.com/ImenHadj/Coconsult-backend.git'            }
        }
    }
}