package com.bezkoder.springjwt.models;


public enum PosteEmployee {
    ADMINISTRATIVE_ASSISTANT,
    EXECUTIVE_ASSISTANT,
    SECRETARY,
    ACCOUNTANT,
    SALES_ASSOCIATE,
    MARKETING_MANAGER,
    HUMAN_RESOURCES_MANAGER,
    IT_ENGINEER,
    WEB_DEVELOPER,
    WAREHOUSE_WORKER,
    FORKLIFT_OPERATOR,
    PRODUCTION_WORKER,
    TEAM_LEADER,
}
